version: "3.9"

services:

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}/s3
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_SERVER_URL}/s3/console
    volumes:
      - /srv/minio/data:/data
    expose:
      - "9000"
      - "9001"
    networks:
      - reels_network

  reels_publisher:
    build: .
    container_name: reels_publisher
    restart: unless-stopped
    depends_on:
      - minio
    ports: 
      - "8000:8000"
    environment:
      STORAGE_ENDPOINT: ${MINIO_SERVER_URL}/s3
      STORAGE_ACCESS_KEY: ${MINIO_ROOT_USER}
      STORAGE_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      STORAGE_BUCKET: reels
    env_file:
      - .env
    volumes:
      - /srv/publisher/data:/data
    networks:
      - reels_network

volumes:
  minio_data:

networks:
  reels_network:
    driver: bridge